<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-04-03 17:49

$extensionPath = t3lib_extMgm::extPath('nkwgok');
return array(
	'tx_nkwgok' => $extensionPath . 'lib/class.tx_nkwgok.php',
	'tx_nkwgok_column' => $extensionPath . 'lib/class.tx_nkwgok_column.php',
	'tx_nkwgok_ff' => $extensionPath . 'lib/class.tx_nkwgok_ff.php',
	'tx_nkwgok_menu' => $extensionPath . 'lib/class.tx_nkwgok_menu.php',
	'tx_nkwgok_tree' => $extensionPath . 'lib/class.tx_nkwgok_tree.php',
	'tx_nkwgok_eid' => $extensionPath . 'lib/get.php',
	'tx_nkwgok_pi1' => $extensionPath . 'pi1/class.tx_nkwgok_pi1.php',
	'tx_nkwgok_checknewcsv' => $extensionPath . 'scheduler/class.tx_nkwgok_checknewcsv.php',
	'tx_nkwgok_convertcsv' => $extensionPath . 'scheduler/class.tx_nkwgok_convertcsv.php',
	'tx_nkwgok_importall' => $extensionPath . 'scheduler/class.tx_nkwgok_importall.php',
	'tx_nkwgok_loadfromopac' => $extensionPath . 'scheduler/class.tx_nkwgok_loadfromopac.php',
	'tx_nkwgok_loadxml' => $extensionPath . 'scheduler/class.tx_nkwgok_loadxml.php',
	'tx_nkwgok_scheduler_convertcsvadditionalparameters' => $extensionPath . 'scheduler/class.tx_nkwgok_scheduler_convertcsvadditionalparameters.php',
	'tx_nkwgok_updatecsv' => $extensionPath . 'scheduler/class.tx_nkwgok_updatecsv.php',
);
?>